export const SET_NEW_QUANTITY = 'SET_NEW_QUANTITY'
export const DELETE_QUANTITY_CHANGE_LOG = 'DELETE_QUANTITY_CHANGE_LOG'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const DELETE_CART = 'DELETE_CART'
