export { Products } from './Management/Products/Products.page'
export { Quantity } from './Management/Quantity/Quantity.page'
export { Orders } from './Management/Orders/Orders.page'
export { SignIn } from './Management/LoginPanel/LoginPanel.page'
export { MainCustomers } from './Customers/MainCustomers/MainCustomers.page'
export {ProductsList} from './Customers/ProductsList/ProducsList.page'
export { default as ProductDetails } from './Customers/ProductDetails/ProductDetails.page'
export { Payment } from './Customers/Payment/Payment.page'
export {ShoppingCart} from './Customers/ShoppingCart/ShoppingCart.page'
export {Checkout} from './Customers/Checkout/Checkout.page'
